name: 'Build'

on:
  push:
    # Only on branches, not tags/releases
    branches:
      - '**'
  pull_request:
    branches:
      - '*'

# Cancel outdated builds for the same branch
concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # Only run the pull-request build if the pull-request was opened from another repository,
    # since we already run this workflow for the branch the pull request was made from.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/libs/
